package com.google.android.gms.internal;

import android.content.Context;
import android.content.SharedPreferences.Editor;
import com.google.android.gms.ads.internal.zzbs;
import com.google.android.gms.cast.framework.media.NotificationOptions;
import com.google.android.gms.fitness.FitnessStatusCodes;
import com.google.android.gms.search.SearchAuth.StatusCodes;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.altbeacon.beacon.BeaconManager;
import org.json.JSONObject;

@zzzn
public final class zzmo {
    private static zzme<String> zzBW = zzme.zza(0, "gads:sdk_core_experiment_id");
    public static final zzme<String> zzBX = zzme.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    private static zzme<Boolean> zzBY = zzme.zza(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
    private static zzme<String> zzBZ = zzme.zza(0, "gads:request_builder:singleton_webview_experiment_id");
    public static final zzme<Long> zzCA = zzme.zza(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final zzme<Boolean> zzCB = zzme.zza(1, "gads:video:acquire_decoder_before_play", Boolean.valueOf(false));
    public static final zzme<Boolean> zzCC = zzme.zza(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
    public static final zzme<Boolean> zzCD = zzme.zza(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
    public static final zzme<String> zzCE = zzme.zza(1, "gads:video:codec_query_mime_types", "");
    public static final zzme<Integer> zzCF = zzme.zza(1, "gads:video:codec_query_minimum_version", 16);
    private static zzme<Boolean> zzCG = zzme.zza(0, "gads:ad_id_app_context:enabled", Boolean.valueOf(false));
    private static zzme<Float> zzCH = zzme.zza(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static zzme<String> zzCI = zzme.zza(0, "gads:ad_id_app_context:experiment_id");
    private static zzme<String> zzCJ = zzme.zzb(0, "gads:looper_for_gms_client:experiment_id");
    public static final zzme<Boolean> zzCK = zzme.zza(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzCL = zzme.zza(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
    private static zzme<Boolean> zzCM = zzme.zza(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
    public static final zzme<String> zzCN = zzme.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final zzme<String> zzCO = zzme.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final zzme<String> zzCP = zzme.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final zzme<Boolean> zzCQ = zzme.zza(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
    public static final zzme<String> zzCR = zzme.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final zzme<Boolean> zzCS = zzme.zza(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
    public static final zzme<Boolean> zzCT = zzme.zza(0, "gads:enable_content_fetching", Boolean.valueOf(true));
    public static final zzme<Integer> zzCU = zzme.zza(0, "gads:content_length_weight", 1);
    public static final zzme<Integer> zzCV = zzme.zza(0, "gads:content_age_weight", 1);
    public static final zzme<Integer> zzCW = zzme.zza(0, "gads:min_content_len", 11);
    public static final zzme<Integer> zzCX = zzme.zza(0, "gads:fingerprint_number", 10);
    public static final zzme<Integer> zzCY = zzme.zza(0, "gads:sleep_sec", 10);
    public static final zzme<Boolean> zzCZ = zzme.zza(1, "gads:enable_content_url_hash", Boolean.valueOf(true));
    private static zzme<Boolean> zzCa = zzme.zza(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
    private static zzme<String> zzCb = zzme.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final zzme<Boolean> zzCc = zzme.zza(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzCd = zzme.zza(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
    public static final zzme<String> zzCe = zzme.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final zzme<Boolean> zzCf = zzme.zza(0, "gads:block_autoclicks", Boolean.valueOf(false));
    private static zzme<String> zzCg = zzme.zza(0, "gads:block_autoclicks_experiment_id");
    private static zzme<String> zzCh = zzme.zza(0, "gads:spam_app_context:experiment_id");
    public static final zzme<Boolean> zzCi = zzme.zza(1, "gads:spam_app_context:enabled", Boolean.valueOf(false));
    private static zzme<Integer> zzCj = zzme.zza(1, "gads:http_url_connection_factory:timeout_millis", (int) StatusCodes.AUTH_DISABLED);
    public static final zzme<String> zzCk = zzme.zza(1, "gads:video_exo_player:version", "1");
    private static zzme<String> zzCl = zzme.zza(0, "gads:video_stream_cache:experiment_id");
    public static final zzme<Integer> zzCm = zzme.zza(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzme<Integer> zzCn = zzme.zza(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzme<Integer> zzCo = zzme.zza(1, "gads:video_stream_exo_allocator:segment_size", 65536);
    public static final zzme<Integer> zzCp = zzme.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzme<Long> zzCq = zzme.zza(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final zzme<Long> zzCr = zzme.zza(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final zzme<Integer> zzCs = zzme.zza(1, "gads:video_stream_cache:connect_timeout_millis", (int) StatusCodes.AUTH_DISABLED);
    public static final zzme<Boolean> zzCt = zzme.zza(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
    public static final zzme<String> zzCu = zzme.zza(1, "gads:video:metric_frame_hash_times", "");
    public static final zzme<Long> zzCv = zzme.zza(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final zzme<Boolean> zzCw = zzme.zza(1, "gads:video:force_watermark", Boolean.valueOf(false));
    public static final zzme<Long> zzCx = zzme.zza(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final zzme<Boolean> zzCy = zzme.zza(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
    public static final zzme<Integer> zzCz = zzme.zza(1, "gads:video:spinner:scale", 4);
    public static final zzme<String> zzDA = zzme.zza(1, "gads:sai:ad_event_id_macro_name", "@gw_fbsaeid@");
    public static final zzme<Long> zzDB = zzme.zza(1, "gads:sai:timeout_ms", 100);
    public static final zzme<Integer> zzDC = zzme.zza(1, "gads:sai:scion_thread_pool_size", 5);
    private static zzme<Integer> zzDD = zzme.zza(0, "gads:webview_cache_version", 0);
    public static final zzme<Boolean> zzDE = zzme.zza(1, "gads:webview_recycle:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzDF = zzme.zza(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
    private static zzme<String> zzDG = zzme.zzb(0, "gads:pan:experiment_id");
    public static final zzme<Boolean> zzDH = zzme.zza(1, "gads:rewarded:adapter_initialization_enabled", Boolean.valueOf(false));
    public static final zzme<Long> zzDI = zzme.zza(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final zzme<Boolean> zzDJ = zzme.zza(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
    public static final zzme<Long> zzDK = zzme.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final zzme<Long> zzDL = zzme.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzme<Boolean> zzDM = zzme.zza(1, "gads:adid_values_in_adrequest:enabled", Boolean.valueOf(false));
    public static final zzme<Long> zzDN = zzme.zza(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final zzme<Boolean> zzDO = zzme.zza(1, "gads:disable_adid_values_in_ms", Boolean.valueOf(false));
    public static final zzme<Boolean> zzDP = zzme.zza(1, "gads:enable_ad_loader_manager", Boolean.valueOf(true));
    private static zzme<Boolean> zzDQ = zzme.zza(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzDR = zzme.zza(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(false));
    public static final zzme<Long> zzDS = zzme.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final zzme<Boolean> zzDT = zzme.zza(1, "gads:interstitial_ad_immersive_mode", Boolean.valueOf(true));
    private static zzme<Boolean> zzDU = zzme.zza(1, "gads:impression_optimization_enabled", Boolean.valueOf(false));
    private static zzme<String> zzDV = zzme.zza(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static zzme<Integer> zzDW = zzme.zza(1, "gads:banner_ad_pool:max_queues", 3);
    private static zzme<Integer> zzDX = zzme.zza(1, "gads:banner_ad_pool:max_pools", 3);
    public static final zzme<Boolean> zzDY = zzme.zza(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzDZ = zzme.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
    public static final zzme<Integer> zzDa = zzme.zza(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzme<Boolean> zzDb = zzme.zza(1, "gads:enable_content_vertical_hash", Boolean.valueOf(true));
    public static final zzme<Integer> zzDc = zzme.zza(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzme<Integer> zzDd = zzme.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzme<String> zzDe = zzme.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzme<String> zzDf = zzme.zza(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final zzme<Boolean> zzDg = zzme.zza(0, "gad:app_index_enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzDh = zzme.zza(1, "gads:content_fetch_disable_get_title_from_webview", Boolean.valueOf(false));
    public static final zzme<Boolean> zzDi = zzme.zza(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
    public static final zzme<Long> zzDj = zzme.zza(0, "gads:app_index:timeout_ms", 1000);
    private static zzme<String> zzDk = zzme.zza(0, "gads:app_index:experiment_id");
    private static zzme<String> zzDl = zzme.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
    public static final zzme<Boolean> zzDm = zzme.zza(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzDn = zzme.zza(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
    public static final zzme<Boolean> zzDo = zzme.zza(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
    private static zzme<String> zzDp = zzme.zza(0, "gads:interstitial_follow_url:experiment_id");
    private static zzme<Boolean> zzDq = zzme.zza(0, "gads:analytics_enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzDr = zzme.zza(0, "gads:ad_key_enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzDs = zzme.zza(1, "gads:sai:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzDt = zzme.zza(1, "gads:sai:banner_ad_enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzDu = zzme.zza(1, "gads:sai:native_ad_enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzDv = zzme.zza(1, "gads:sai:interstitial_ad_enabled", Boolean.valueOf(true));
    public static final zzme<String> zzDw = zzme.zza(1, "gads:sai:click_ping_schema", "[\"/aclk\",\"/pcs/click\"]");
    public static final zzme<String> zzDx = zzme.zza(1, "gads:sai:impression_ping_schema", "[\"/adview\"]");
    public static final zzme<Boolean> zzDy = zzme.zza(1, "gads:sai:click_gmsg_enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzDz = zzme.zza(1, "gads:sai:using_macro:enabled", Boolean.valueOf(false));
    private static zzme<Boolean> zzEA = zzme.zza(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzEB = zzme.zza(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzEC = zzme.zza(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
    private static zzme<String> zzED = zzme.zza(0, "gads:gmsg:video_meta:experiment_id");
    private static zzme<Long> zzEE = zzme.zza(1, "gads:network:cache_prediction_duration_s", 300);
    public static final zzme<Long> zzEF = zzme.zza(1, "gads:network:network_prediction_timeout_ms", 2000);
    public static final zzme<Boolean> zzEG = zzme.zza(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
    public static final zzme<Boolean> zzEH = zzme.zza(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
    public static final zzme<Boolean> zzEI = zzme.zza(1, "gads:bypass_adrequest_service_for_inlined_mediation", Boolean.valueOf(true));
    public static final zzme<Long> zzEJ = zzme.zza(0, "gads:resolve_future:default_timeout_ms", (long) NotificationOptions.SKIP_STEP_THIRTY_SECONDS_IN_MS);
    public static final zzme<Long> zzEK = zzme.zza(0, "gads:ad_loader:timeout_ms", 60000);
    public static final zzme<Long> zzEL = zzme.zza(0, "gads:rendering:timeout_ms", 60000);
    public static final zzme<Boolean> zzEM = zzme.zza(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
    public static final zzme<Long> zzEN = zzme.zza(1, "gads:gestures:task_timeout", 2000);
    public static final zzme<Boolean> zzEO = zzme.zza(1, "gads:gestures:encrypt_size_limit:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzEP = zzme.zza(1, "gads:gestures:adb_query:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzEQ = zzme.zza(1, "gads:gestures:adb_click:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzER = zzme.zza(1, "gads:gestures:orn_caching:enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzES = zzme.zza(1, "gads:gestures:oc:enabled", Boolean.valueOf(false));
    public static final zzme<Integer> zzET = zzme.zza(1, "gads:gestures:ts", 1);
    public static final zzme<Boolean> zzEU = zzme.zza(1, "gads:gestures:td:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzEV = zzme.zza(1, "gads:gestures:tdvs:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzEW = zzme.zza(1, "gads:gestures:tuvs:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzEX = zzme.zza(1, "gads:gestures:tvvs:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzEY = zzme.zza(1, "gads:gestures:vd:enabled", Boolean.valueOf(false));
    private static zzme<String> zzEZ = zzme.zza(1, "gads:gestures:pk", "");
    public static final zzme<String> zzEa = zzme.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final zzme<String> zzEb = zzme.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final zzme<Integer> zzEc = zzme.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final zzme<Integer> zzEd = zzme.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final zzme<Integer> zzEe = zzme.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final zzme<String> zzEf = zzme.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final zzme<Integer> zzEg = zzme.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final zzme<Integer> zzEh = zzme.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final zzme<Long> zzEi = zzme.zza(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    public static final zzme<Long> zzEj = zzme.zza(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    public static final zzme<Float> zzEk = zzme.zza(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final zzme<Float> zzEl = zzme.zza(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    private static zzme<Integer> zzEm = zzme.zza(1, "gads:heap_wastage:bytes", 0);
    public static final zzme<String> zzEn = zzme.zza(1, "gads:spherical_video:vertex_shader", "");
    public static final zzme<String> zzEo = zzme.zza(1, "gads:spherical_video:fragment_shader", "");
    public static final zzme<Boolean> zzEp = zzme.zza(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzEq = zzme.zza(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
    public static final zzme<Long> zzEr = zzme.zza(1, "gads:position_watcher:throttle_ms", 200);
    public static final zzme<Boolean> zzEs = zzme.zza(1, "gads:include_lock_screen_apps_for_visibility", Boolean.valueOf(true));
    public static final zzme<Boolean> zzEt = zzme.zza(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
    public static final zzme<Long> zzEu = zzme.zza(0, "gads:device_info_caching_expiry_ms:expiry", (long) BeaconManager.DEFAULT_BACKGROUND_BETWEEN_SCAN_PERIOD);
    public static final zzme<Boolean> zzEv = zzme.zza(0, "gads:gen204_signals:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzEw = zzme.zza(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
    private static zzme<Boolean> zzEx = zzme.zza(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
    private static zzme<Boolean> zzEy = zzme.zza(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
    private static zzme<Boolean> zzEz = zzme.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
    public static final zzme<String> zzFA = zzme.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final zzme<Boolean> zzFB = zzme.zza(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
    public static final zzme<Boolean> zzFC = zzme.zza(1, "gads:enable_store_active_view_state", Boolean.valueOf(false));
    public static final zzme<Boolean> zzFD = zzme.zza(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
    public static final zzme<Boolean> zzFE = zzme.zza(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
    public static final zzme<Long> zzFF = zzme.zza(0, "gads:method_tracing:duration_ms", (long) NotificationOptions.SKIP_STEP_THIRTY_SECONDS_IN_MS);
    public static final zzme<Integer> zzFG = zzme.zza(0, "gads:method_tracing:count", 5);
    public static final zzme<Integer> zzFH = zzme.zza(0, "gads:method_tracing:filesize", 134217728);
    private static zzme<Boolean> zzFI = zzme.zza(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
    private static zzme<String> zzFJ = zzme.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final zzme<Long> zzFK = zzme.zza(1, "gads:auto_location_timeout", 2000);
    private static zzme<String> zzFL = zzme.zzb(1, "gads:auto_location_timeout:experiment_id");
    private static zzme<Long> zzFM = zzme.zza(1, "gads:auto_location_interval", -1);
    private static zzme<String> zzFN = zzme.zzb(1, "gads:auto_location_interval:experiment_id");
    public static final zzme<Boolean> zzFO = zzme.zza(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
    private static zzme<String> zzFP = zzme.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final zzme<Long> zzFQ = zzme.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    private static zzme<String> zzFR = zzme.zza(0, "gads:afs:csa:experiment_id");
    public static final zzme<String> zzFS = zzme.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final zzme<String> zzFT = zzme.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final zzme<String> zzFU = zzme.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final zzme<String> zzFV = zzme.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final zzme<String> zzFW = zzme.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final zzme<Long> zzFX = zzme.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
    private static zzme<Boolean> zzFY = zzme.zza(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
    private static zzme<Boolean> zzFZ = zzme.zza(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
    public static final zzme<Boolean> zzFa = zzme.zza(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzFb = zzme.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzFc = zzme.zza(0, "gass:enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzFd = zzme.zza(0, "gass:enable_int_signal", Boolean.valueOf(true));
    public static final zzme<Boolean> zzFe = zzme.zza(0, "gass:enable_ad_attestation_signal", Boolean.valueOf(true));
    private static zzme<Boolean> zzFf = zzme.zza(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
    private static zzme<Boolean> zzFg = zzme.zza(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzFh = zzme.zza(0, "gads:support_screen_shot", Boolean.valueOf(true));
    public static final zzme<Boolean> zzFi = zzme.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
    private static zzme<String> zzFj = zzme.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static zzme<String> zzFk = zzme.zza(1, "gads:sdk_core_constants:experiment_id");
    public static final zzme<String> zzFl = zzme.zza(1, "gads:sdk_core_constants:caps", "");
    public static final zzme<Long> zzFm = zzme.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final zzme<Boolean> zzFn = zzme.zza(0, "gads:js_flags:mf", Boolean.valueOf(false));
    public static final zzme<Boolean> zzFo = zzme.zza(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
    private static zzme<String> zzFp = zzme.zza(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final zzme<String> zzFq = zzme.zza(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static zzme<String> zzFr = zzme.zza(1, "gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
    public static final zzme<String> zzFs = zzme.zza(1, "gads:native:video_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
    public static final zzme<Boolean> zzFt = zzme.zza(1, "gads:singleton_webview_native", Boolean.valueOf(false));
    public static final zzme<Boolean> zzFu = zzme.zza(1, "gads:native_initialize_webview_request_time", Boolean.valueOf(false));
    private static zzme<String> zzFv = zzme.zza(1, "gads:singleton_webview_native:experiment_id");
    public static final zzme<Boolean> zzFw = zzme.zza(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
    public static final zzme<Boolean> zzFx = zzme.zza(1, "gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
    public static final zzme<Boolean> zzFy = zzme.zza(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
    public static final zzme<Integer> zzFz = zzme.zza(1, "gads:native_video_load_timeout", 10);
    public static final zzme<Boolean> zzGA = zzme.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
    public static final zzme<Integer> zzGB = zzme.zza(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzme<Boolean> zzGC = zzme.zza(1, "gads:clearcut_logging:enabled", Boolean.valueOf(false));
    private static zzme<Boolean> zzGD = zzme.zza(1, "gads:clearcut_abtest:enabled", Boolean.valueOf(false));
    public static final zzme<Integer> zzGE = zzme.zza(1, "gads:clearcut_messageTime:ms", 60000);
    public static final zzme<Boolean> zzGF = zzme.zza(0, "gad:force_local_ad_request_service:enabled", Boolean.valueOf(false));
    public static final zzme<Integer> zzGG = zzme.zza(1, "gad:http_redirect_max_count:times", 8);
    private static byte[] zzGH;
    private static zzme<Boolean> zzGa = zzme.zza(1, "gads:parental_controls:cache_results", Boolean.valueOf(true));
    public static final zzme<Long> zzGb = zzme.zza(1, "gads:parental_controls:timeout", 2000);
    public static final zzme<String> zzGc = zzme.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    public static final zzme<Long> zzGd = zzme.zza(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
    public static final zzme<Boolean> zzGe = zzme.zza(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
    public static final zzme<Boolean> zzGf = zzme.zza(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
    private static zzme<Integer> zzGg = zzme.zza(1, "gads:cache:ad_request_timeout_millis", 250);
    private static zzme<Integer> zzGh = zzme.zza(1, "gads:cache:max_concurrent_downloads", 10);
    private static zzme<Long> zzGi = zzme.zza(1, "gads:cache:javascript_timeout_millis", 5000);
    public static final zzme<Boolean> zzGj = zzme.zza(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
    public static final zzme<Boolean> zzGk = zzme.zza(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
    public static final zzme<Boolean> zzGl = zzme.zza(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
    public static final zzme<Long> zzGm = zzme.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    private static zzme<Boolean> zzGn = zzme.zza(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
    public static final zzme<Boolean> zzGo = zzme.zza(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzGp = zzme.zza(1, "gads:chrome_custom_tabs_browser:enabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzGq = zzme.zza(1, "gads:chrome_custom_tabs:disabled", Boolean.valueOf(false));
    public static final zzme<Boolean> zzGr = zzme.zza(1, "gads:drx_in_app_preview:enabled", Boolean.valueOf(true));
    public static final zzme<Boolean> zzGs = zzme.zza(1, "gads:drx_debug_signals:enabled", Boolean.valueOf(true));
    public static final zzme<String> zzGt = zzme.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzme<String> zzGu = zzme.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzme<String> zzGv = zzme.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzme<String> zzGw = zzme.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzme<Integer> zzGx = zzme.zza(1, "gads:drx_debug:timeout_ms", (int) FitnessStatusCodes.NEEDS_OAUTH_PERMISSIONS);
    public static final zzme<Integer> zzGy = zzme.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzme<Boolean> zzGz = zzme.zza(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));

    public static void initialize(Context context) {
        zzait.zzb(new zzmp(context));
        int intValue = ((Integer) zzbs.zzbL().zzd(zzEm)).intValue();
        if (intValue > 0 && zzGH == null) {
            zzGH = new byte[intValue];
        }
    }

    public static void zza(Context context, int i, JSONObject jSONObject) {
        zzbs.zzbJ();
        Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzbs.zzbK().zza(edit, 1, jSONObject);
        zzbs.zzbJ();
        edit.commit();
    }

    public static List<String> zzdJ() {
        return zzbs.zzbK().zzdJ();
    }

    public static List<String> zzdK() {
        return zzbs.zzbK().zzdK();
    }
}
