package com.google.android.gms.games.internal.player;

import android.text.TextUtils;

public final class zze {
    public final String name;
    public final String title;
    public final String zzbcA;
    public final String zzbcB;
    public final String zzbcC;
    public final String zzbcD;
    public final String zzbcE;
    public final String zzbcF;
    public final String zzbcG;
    public final String zzbca;
    public final String zzbcb;
    public final String zzbcc;
    public final String zzbcd;
    public final String zzbce;
    public final String zzbcf;
    public final String zzbcg;
    public final String zzbch;
    public final String zzbci;
    public final String zzbcj;
    public final String zzbck;
    public final String zzbcl;
    public final String zzbcm;
    public final String zzbcn;
    public final String zzbco;
    public final String zzbcp;
    private String zzbcq;
    public final String zzbcr;
    public final String zzbcs;
    public final String zzbct;
    public final String zzbcu;
    public final String zzbcv;
    public final String zzbcw;
    public final String zzbcx;
    public final String zzbcy;
    public final String zzbcz;

    public zze(String str) {
        if (TextUtils.isEmpty(str)) {
            this.zzbca = "external_player_id";
            this.zzbcb = "profile_name";
            this.zzbcc = "profile_icon_image_uri";
            this.zzbcd = "profile_icon_image_url";
            this.zzbce = "profile_hi_res_image_uri";
            this.zzbcf = "profile_hi_res_image_url";
            this.zzbcg = "last_updated";
            this.zzbch = "is_in_circles";
            this.zzbci = "played_with_timestamp";
            this.zzbcj = "current_xp_total";
            this.zzbck = "current_level";
            this.zzbcl = "current_level_min_xp";
            this.zzbcm = "current_level_max_xp";
            this.zzbcn = "next_level";
            this.zzbco = "next_level_max_xp";
            this.zzbcp = "last_level_up_timestamp";
            this.title = "player_title";
            this.zzbcq = "has_all_public_acls";
            this.zzbcr = "is_profile_visible";
            this.zzbcs = "most_recent_external_game_id";
            this.zzbct = "most_recent_game_name";
            this.zzbcu = "most_recent_activity_timestamp";
            this.zzbcv = "most_recent_game_icon_uri";
            this.zzbcw = "most_recent_game_hi_res_uri";
            this.zzbcx = "most_recent_game_featured_uri";
            this.zzbcy = "has_debug_access";
            this.zzbcz = "gamer_tag";
            this.name = "real_name";
            this.zzbcA = "banner_image_landscape_uri";
            this.zzbcB = "banner_image_landscape_url";
            this.zzbcC = "banner_image_portrait_uri";
            this.zzbcD = "banner_image_portrait_url";
            this.zzbcE = "gamer_friend_status";
            this.zzbcF = "gamer_friend_update_timestamp";
            str = "is_muted";
        } else {
            String valueOf = String.valueOf(str);
            String valueOf2 = String.valueOf("external_player_id");
            this.zzbca = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("profile_name");
            this.zzbcb = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("profile_icon_image_uri");
            this.zzbcc = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("profile_icon_image_url");
            this.zzbcd = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("profile_hi_res_image_uri");
            this.zzbce = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("profile_hi_res_image_url");
            this.zzbcf = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("last_updated");
            this.zzbcg = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("is_in_circles");
            this.zzbch = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("played_with_timestamp");
            this.zzbci = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("current_xp_total");
            this.zzbcj = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("current_level");
            this.zzbck = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("current_level_min_xp");
            this.zzbcl = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("current_level_max_xp");
            this.zzbcm = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("next_level");
            this.zzbcn = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("next_level_max_xp");
            this.zzbco = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("last_level_up_timestamp");
            this.zzbcp = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("player_title");
            this.title = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("has_all_public_acls");
            this.zzbcq = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("is_profile_visible");
            this.zzbcr = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("most_recent_external_game_id");
            this.zzbcs = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("most_recent_game_name");
            this.zzbct = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("most_recent_activity_timestamp");
            this.zzbcu = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("most_recent_game_icon_uri");
            this.zzbcv = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("most_recent_game_hi_res_uri");
            this.zzbcw = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("most_recent_game_featured_uri");
            this.zzbcx = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("has_debug_access");
            this.zzbcy = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("gamer_tag");
            this.zzbcz = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("real_name");
            this.name = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("banner_image_landscape_uri");
            this.zzbcA = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("banner_image_landscape_url");
            this.zzbcB = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("banner_image_portrait_uri");
            this.zzbcC = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("banner_image_portrait_url");
            this.zzbcD = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("gamer_friend_status");
            this.zzbcE = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            valueOf = String.valueOf(str);
            valueOf2 = String.valueOf("gamer_friend_update_timestamp");
            this.zzbcF = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
            str = String.valueOf(str);
            valueOf = String.valueOf("is_muted");
            str = valueOf.length() != 0 ? str.concat(valueOf) : new String(str);
        }
        this.zzbcG = str;
    }
}
